version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: parking-app-postgres
    environment:
      POSTGRES_DB:   ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - parking-app-data:/var/lib/postgresql/data
    restart: unless-stopped 
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: parking-app-rabbitmq
#    ports:
#      - "5672:5672" 
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    restart: unless-stopped

volumes:
  parking-app-data:

  #  parking-app-backend:
  #  container_name: parking-app-backend
  #  build:
  #    context: .
  #    dockerfile: apps/parking-app-back/Dockerfile
  #  ports:
  #    - "${BACK_PORT:-3000}:3000"
  #  env_file:
  #    - .env
  #  depends_on:
  #    - postgres
  #  restart: unless-stopped
